# Generated by Django 4.0.4 on 2022-06-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_category_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slig',
            new_name='slug',
        ),
    ]
